### ISSUE TITLE
Need example usage

### ISSUE THREAD

**Issue by sundarseswaran** [platdesign/Micky#1]
@platdesign -- was surprised to find this package in npm.  looks interesting and trying to see if I can make use of it. 

By chance do you have any sample usage for this module?

**Comment by platdesign** [comment]
@sundarseswaran Sorry, it was for testing purpose only (needs security credentials in frontend). But you can use the angular-wrappers [angular-oz](https://github.com/platdesign/angular-oz) and [angular-hawk](https://github.com/platdesign/angular-hawk) to build a real client which starts with an oz-ticket from your backend.

**Comment by sundarseswaran** [comment]
Sounds good. Thank you very much for your response.
